[package]
name = "hello-mud"
version = "0.1.0"
authors = ["moonpatroller <mrjoshbgoldstein@gmail.com>"]
edition = '2018'

[dependencies]
serde_json = "1.0.39"
serde = { version = "1.0", features = ["derive"] }

